version: "3.8"
services:
  postgres-db:
    container_name: "postgres-db-cont"
    image: postgres:13.8
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=123
    volumes:
      - pg-db:/var/lib/postgresql/data
    networks:
      - my-net
  spring-api:
    depends_on:
      - postgres-db
    container_name: "spring-api-cont"
    build:
      context: ./docker
      dockerfile: spring-dockerfile
    ports:
      - "8081:8080"
    volumes:
      - app-files:/src/main/resources/images
    networks:
      - my-net
  react-ui:
    depends_on:
      - spring-api
    container_name: "react-ui-cont"
    build:
      context: ./docker
      dockerfile: react-dockerfile
    ports:
      - "3001:3000"
    networks:
      - my-net
volumes:
  pg-db:
  app-files:
networks:
  my-net: